# Auxiliary Support
- type: roleLoadout
  id: JobCMAuxiliarySupportOfficer
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMDropshipCrewChief
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMPilotDropship
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMPilotGunship
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMIntelOfficer
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

# Command
- type: roleLoadout
  id: JobCMCommandingOfficer
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - MarineLeatherBackpack
  - CommandingOfficerIDRMC
  - CommandingOfficerWeaponRMC
  - CommandingOfficerRoleSpecificRMC
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMExecutiveOfficer
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMStaffOfficer
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

# Engineering
- type: roleLoadout
  id: JobCMChiefEngineer
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMMaintTech
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMOrdnanceTech
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

# Squad Roles
- type: roleLoadout
  id: JobCMCombatTech
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMFireteamLeader
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMHospitalCorpsman
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineMedicBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMRifleman
  points: 7
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMSmartGunOperator
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMSquadLeader
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMWeaponsSpecialist
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

# Medical
- type: roleLoadout
  id: JobCMCMO
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMDoctor
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMNurse
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMResearcher
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

# Military Police
- type: roleLoadout
  id: JobCMProvostInspector
  points: 7
  groups:
  - ProvostRoleSpecificOuterwearRMC
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMChiefMP
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - MarineSecurityBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - ChiefMPRoleSpecificRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMMilitaryPolice
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineSecurityBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMMilitaryWarden
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineSecurityBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

# Other
- type: roleLoadout
  id: JobCMCorrespondent
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineLeatherBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - CivilianOnlyRMC

- type: roleLoadout
  id: JobCMLiaison
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineLeatherBackpack
  - LiaisonRoleSpecificRMC
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - CivilianOnlyRMC

- type: roleLoadout
  id: JobCMMessTech
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMSeniorEnlistedAdvisor
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - MarineBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobRMCJobSynthetic
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - SynthBackpackRMC
  - SynthHeadwearRMC
  - SynthGlassesRMC
  - SynthMasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - SynthUniformRMC
  - SynthUniformAccessoriesRMC
  - SynthSuitsRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

# Requsitions
- type: roleLoadout
  id: JobCMCargoTech
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMQuartermaster
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - MarineTechnicianBackpack
  - HeadwearRMC
  - EyewearRMC
  - MasksRMC
  - HelmetGarbsRMC
  - AccessoriesRMC
  - PaperworkRMC
  - RecreationalRMC
  - PlushiesRMC
  - WeaponsRMC
  - CannedDrinksRMC
  - FlasksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

# Survivors
# They don't have access to some loadout categories
- type: roleLoadout
  id: JobCMSurvivor
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - EyewearRMC
  - MasksRMC
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - CivilianOnlyRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobRMCJobSyntheticColony
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - EyewearRMC
  - MasksRMC
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - CivilianOnlyRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMSurvivorCorporate
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - EyewearRMC
  - MasksRMC
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - CivilianOnlyRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMSurvivorDoctor
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - EyewearRMC
  - MasksRMC
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - CivilianOnlyRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMSurvivorEngineer
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - EyewearRMC
  - MasksRMC
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - CivilianOnlyRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMSurvivorScientist
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - EyewearRMC
  - MasksRMC
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - CivilianOnlyRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobCMSurvivorSecurity
  points: 9 # 7 в РМС, зміна білду Січі
  groups:
  - EyewearRMC
  - MasksRMC
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - CivilianOnlyRMC
  - MeleeWeaponsRMC

- type: roleLoadout
  id: JobRMCSurvivorCommandingOfficer
  points: 11 # 7 в РМС, зміна білду Січі
  groups:
  - EyewearRMC
  - MasksRMC
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksRMC
  - FoodSweetsRMC
  - FoodPackagedRMC
  - FoodHealthyRMC
  - RMCLoadoutGroupPins
  - SmokablesRMC
  - MiscellaneousRMC
  - MeleeWeaponsRMC

# PVE

- type: roleLoadout
  id: JobCMPVERifleman
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMPVEHospitalCorpsman
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMPVESmartGunOperator
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMPVESquadLeader
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMPVESectionSergeant
  points: 20
  groups:
  - MarineBackpack
  - HeadwearRMCPVE
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins

- type: roleLoadout
  id: JobCMPVEPlatoonCommander
  points: 20
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HelmetGarbsRMCPVE
  - AccessoriesRMCPVE
  - PlushiesRMC
  - WeaponsRMC
  - RMCLoadoutGroupPins
