# Whisper
- type: rank
  id: RMCRankProvostSectorMarshal
  name: Маршал Сектору
  prefix: ПвМС.
  paygrade: O9

# Any admin with high law understanding
- type: rank
  id: RMCRankProvostSeniorMarshal
  name: Старший Маршал
  prefix: ПвСт.М.
  paygrade: O8

# Any admin with low law understanding, or wanting a lower rank
- type: rank
  id: RMCRankProvostMarshal
  name: Маршал
  prefix: ПвМ.
  paygrade: O7

# Any whitelisted CO
- type: rank
  id: RMCRankProvostDeputyMarshal
  name: Заступник Маршала
  prefix: ПвЗМ.
  paygrade: O6

# Any player with high law understanding
- type: rank
  id: RMCRankProvostChiefInspector
  name: Головний Інспектор
  prefix: ГІПв.
  paygrade: O6

# Any player with medium-low law understanding
- type: rank
  id: RMCRankProvostInspector
  name: Інспектор Провосту
  prefix: ІПв.
  paygrade: O4

# Fax responder
- type: rank
  id: RMCRankProvostCommunicationsOfficer
  name: Офіцер Комунікацій
  prefix: ОфКом
  paygrade: O2

# Any player with low law understanding, with guidance
- type: rank
  id: RMCRankProvostAdvisor
  name: Сержант-Майор
  prefix: С-нтМ-р.
  paygrade: E9E

# Any player with given objective, possible team leader
- type: rank
  id: RMCRankProvostProvostTeamLeader
  name: Майстер-Сержант
  prefix: М.С-нт.
  paygrade: E8

# Any player with given objective, squad member
- type: rank
  id: RMCRankProvostProvostEnforcer
  name: Штаб-Сержант
  prefix: Шт.С-нт.
  paygrade: E6
